### ISSUE TITLE
Refactor config.go

### ISSUE THREAD

**Issue by soupdiver** [cloudradar-monitoring/cagent#38]
Refactor and split up `ReadConfigFromFile` in `config.go`.
Similar task already done in cloudradar-monitoring/frontman#19

**Comment by troian** [comment]
Done

**Comment by soupdiver** [comment]
@troian Please request review from me but don't re-assign the ticket :)

**Comment by soupdiver** [comment]
@troian No need to assign me here. Just reference and close the ticket in the PR and request my review in the PR

**Comment by soupdiver** [comment]
Closed by #37
