### ISSUE TITLE
top pkg issues

### ISSUE THREAD

**Issue by requilence** [cloudradar-monitoring/cagent#70]
I have some problems with top pkg that needs to be solved for https://github.com/cloudradar-monitoring/cagent/pull/69 to be merged

1. Need to add lowercase-naming json struct tags for `ProcessInfo` struct. Any reason you renamed process `Name` into `Identifier`? This could probably confuse both devs & users.

2. I got a lot of logs like this on Linux. I didn't dig  why this procs not exist (maybe very short-lived) but probably need to omit them
<img width="893" alt="image" src="https://user-images.githubusercontent.com/1025231/51800379-a4cd3100-2236-11e9-8c39-ddb50644288d.png">

3. I made a sorting of `GetProcesses()` on my side, but it feels like it should be done on `top` side. The same way it is done in the `top` utility by default.

**Comment by soupdiver** [comment]
> Need to add lowercase-naming json struct tags for ProcessInfo struct

done

> Any reason you renamed process Name into Identifier?

Not entire sure, renamed to `Name`

> but probably need to omit them

done

> I made a sorting of GetProcesses() on my side

Not sure what you mean. `GetProcesses()` is not the method you should use. `GetProcesses()` returns the raw process data based on which I calculate 5min average for example.
You should use `HighestNLoad(n int) []*ProcessInfo` return the top N processes load-wise.
This method also already sorts by `Load`.

**Comment by requilence** [comment]
@soupdiver  I can't find the mention of `HighestNLoad(n int)  []*ProcessInfo` in the master branch.

**Comment by requilence** [comment]
Ok, I see it in your last PR
