### ISSUE TITLE
CI: Changelog is lost after MSI upload

### ISSUE THREAD

**Issue by requilence** [cloudradar-monitoring/cagent#87]
@soupdiver Maybe you can address  this within https://github.com/cloudradar-monitoring/cagent/pull/84

**Comment by soupdiver** [comment]
I'm happy to do so if you can give some some more context... @requilence

**Comment by requilence** [comment]
After gorelease, but before MSI upload:
<img width="569" alt="screenshot 2019-02-07 at 18 29 10" src="https://user-images.githubusercontent.com/1025231/52426577-e39c9a00-2b06-11e9-9aaa-e80e1d2db2dc.png">

After MSI upload:
<img width="663" alt="screenshot 2019-02-07 at 18 33 00" src="https://user-images.githubusercontent.com/1025231/52426602-ec8d6b80-2b06-11e9-87fa-8125d85106ae.png">

**Comment by soupdiver** [comment]
The problem is not the MSI upload.
When executing `github-release edit` in the end, the changelog is not preserved... will check
